# Generated by Django 3.2.5 on 2021-07-17 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalWeapon',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='characters.item')),
            ],
            bases=('characters.item',),
        ),
        migrations.CreateModel(
            name='Arms',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='characters.item')),
            ],
            bases=('characters.item',),
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='characters.item')),
            ],
            bases=('characters.item',),
        ),
        migrations.CreateModel(
            name='Boots',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='characters.item')),
            ],
            bases=('characters.item',),
        ),
        migrations.CreateModel(
            name='Cloack',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='characters.item')),
            ],
            bases=('characters.item',),
        ),
        migrations.CreateModel(
            name='Head',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='characters.item')),
            ],
            bases=('characters.item',),
        ),
        migrations.CreateModel(
            name='Legs',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='characters.item')),
            ],
            bases=('characters.item',),
        ),
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='characters.item')),
            ],
            bases=('characters.item',),
        ),
        migrations.CreateModel(
            name='PrimaryWeapon',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='characters.item')),
            ],
            bases=('characters.item',),
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('inventory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='characters.inventory')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='characters.item')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('exp', models.IntegerField()),
                ('level', models.IntegerField()),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='characters.equipment')),
                ('inventory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='characters.inventory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='additionalWeapon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='characters.additionalweapon'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='arms',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='characters.arms'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='body',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='characters.body'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='boots',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='characters.boots'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='cloack',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='characters.cloack'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='head',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='characters.head'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='legs',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='characters.legs'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='mask',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='characters.mask'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='primaryWeapon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='characters.primaryweapon'),
        ),
    ]
